// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayReq struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayReq) Reset()         { *m = SayReq{} }
func (m *SayReq) String() string { return proto.CompactTextString(m) }
func (*SayReq) ProtoMessage()    {}
func (*SayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *SayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayReq.Unmarshal(m, b)
}
func (m *SayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayReq.Marshal(b, m, deterministic)
}
func (m *SayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayReq.Merge(m, src)
}
func (m *SayReq) XXX_Size() int {
	return xxx_messageInfo_SayReq.Size(m)
}
func (m *SayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SayReq.DiscardUnknown(m)
}

var xxx_messageInfo_SayReq proto.InternalMessageInfo

func (m *SayReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SayResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResp) Reset()         { *m = SayResp{} }
func (m *SayResp) String() string { return proto.CompactTextString(m) }
func (*SayResp) ProtoMessage()    {}
func (*SayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *SayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResp.Unmarshal(m, b)
}
func (m *SayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResp.Marshal(b, m, deterministic)
}
func (m *SayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResp.Merge(m, src)
}
func (m *SayResp) XXX_Size() int {
	return xxx_messageInfo_SayResp.Size(m)
}
func (m *SayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResp.DiscardUnknown(m)
}

var xxx_messageInfo_SayResp proto.InternalMessageInfo

func (m *SayResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddIntNumsRequest struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIntNumsRequest) Reset()         { *m = AddIntNumsRequest{} }
func (m *AddIntNumsRequest) String() string { return proto.CompactTextString(m) }
func (*AddIntNumsRequest) ProtoMessage()    {}
func (*AddIntNumsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *AddIntNumsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIntNumsRequest.Unmarshal(m, b)
}
func (m *AddIntNumsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIntNumsRequest.Marshal(b, m, deterministic)
}
func (m *AddIntNumsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIntNumsRequest.Merge(m, src)
}
func (m *AddIntNumsRequest) XXX_Size() int {
	return xxx_messageInfo_AddIntNumsRequest.Size(m)
}
func (m *AddIntNumsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIntNumsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIntNumsRequest proto.InternalMessageInfo

func (m *AddIntNumsRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddIntNumsRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddIntNumsResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIntNumsResponse) Reset()         { *m = AddIntNumsResponse{} }
func (m *AddIntNumsResponse) String() string { return proto.CompactTextString(m) }
func (*AddIntNumsResponse) ProtoMessage()    {}
func (*AddIntNumsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *AddIntNumsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIntNumsResponse.Unmarshal(m, b)
}
func (m *AddIntNumsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIntNumsResponse.Marshal(b, m, deterministic)
}
func (m *AddIntNumsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIntNumsResponse.Merge(m, src)
}
func (m *AddIntNumsResponse) XXX_Size() int {
	return xxx_messageInfo_AddIntNumsResponse.Size(m)
}
func (m *AddIntNumsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIntNumsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIntNumsResponse proto.InternalMessageInfo

func (m *AddIntNumsResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *AddIntNumsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*SayReq)(nil), "proto.SayReq")
	proto.RegisterType((*SayResp)(nil), "proto.SayResp")
	proto.RegisterType((*AddIntNumsRequest)(nil), "proto.AddIntNumsRequest")
	proto.RegisterType((*AddIntNumsResponse)(nil), "proto.AddIntNumsResponse")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x89, 0xd5, 0x2e, 0xfb, 0x50, 0x59, 0xdf, 0x41, 0xe2, 0x9e, 0x24, 0x7a, 0xf0, 0xb4,
	0x82, 0xde, 0x85, 0x1e, 0xbd, 0x78, 0x48, 0xfd, 0x03, 0x69, 0xf3, 0x40, 0x21, 0x26, 0x69, 0x92,
	0x2a, 0xfd, 0xf7, 0xd2, 0xa4, 0x42, 0x41, 0xf1, 0x94, 0x7c, 0xcc, 0x0c, 0x6f, 0x06, 0x76, 0x6f,
	0x64, 0x8c, 0xfb, 0x72, 0xc1, 0xe8, 0x83, 0x0f, 0x2e, 0x39, 0x3c, 0xc9, 0x8f, 0x10, 0x50, 0xb7,
	0x6a, 0x92, 0x34, 0x20, 0x87, 0x4d, 0xef, 0x6c, 0x22, 0x9b, 0x38, 0xbb, 0x66, 0x77, 0x5b, 0xf9,
	0x83, 0xe2, 0x06, 0x36, 0xd9, 0x13, 0xfd, 0x3f, 0xa6, 0x7b, 0xb8, 0x68, 0xb4, 0x7e, 0xb6, 0xe9,
	0x65, 0xfc, 0x88, 0x92, 0x86, 0x91, 0x62, 0xc2, 0x53, 0x60, 0x2a, 0x1b, 0x2b, 0xc9, 0xd4, 0x4c,
	0x1d, 0x3f, 0x2a, 0xd4, 0x89, 0x27, 0xc0, 0x75, 0x20, 0x7a, 0x67, 0x23, 0xe1, 0x25, 0xd4, 0x81,
	0xe2, 0x68, 0xd2, 0x12, 0x5b, 0x08, 0x77, 0x50, 0x51, 0x08, 0x39, 0xbd, 0x95, 0xf3, 0xf7, 0xc1,
	0xc1, 0xf1, 0xeb, 0x7c, 0xe3, 0x16, 0xaa, 0x56, 0x4d, 0x78, 0x56, 0x76, 0x1d, 0xca, 0x9a, 0xfd,
	0xf9, 0x1a, 0xa3, 0xc7, 0x06, 0xa0, 0xd1, 0xba, 0xa5, 0xf0, 0xf9, 0xde, 0x13, 0xf2, 0x45, 0xfd,
	0xd5, 0x78, 0x7f, 0xf5, 0x87, 0x52, 0xaa, 0x75, 0x75, 0x56, 0x1e, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0x41, 0x87, 0xdb, 0x4c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayResp, error)
	AddService(ctx context.Context, in *AddIntNumsRequest, opts ...grpc.CallOption) (*AddIntNumsResponse, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Say(ctx context.Context, in *SayReq, opts ...grpc.CallOption) (*SayResp, error) {
	out := new(SayResp)
	err := c.cc.Invoke(ctx, "/proto.Test/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) AddService(ctx context.Context, in *AddIntNumsRequest, opts ...grpc.CallOption) (*AddIntNumsResponse, error) {
	out := new(AddIntNumsResponse)
	err := c.cc.Invoke(ctx, "/proto.Test/AddService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	Say(context.Context, *SayReq) (*SayResp, error)
	AddService(context.Context, *AddIntNumsRequest) (*AddIntNumsResponse, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) Say(ctx context.Context, req *SayReq) (*SayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (*UnimplementedTestServer) AddService(ctx context.Context, req *AddIntNumsRequest) (*AddIntNumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddService not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Test/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Say(ctx, req.(*SayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_AddService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIntNumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).AddService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Test/AddService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).AddService(ctx, req.(*AddIntNumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Test_Say_Handler,
		},
		{
			MethodName: "AddService",
			Handler:    _Test_AddService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
